#docker run --name goferPostgres -p 5433:5433 -e POSTGRES_USER=senya -e POSTGRES_PASSWORD=1q2w3e4r5t -e POSTGRES_DB=gofermat -d postgres:16
POSTGRES_CONFIG:
  POSTGRES_DB: "gofermat"
  POSTGRES_USER: "senya"
  POSTGRES_PASSWORD: "1q2w3e4r5t"
  PORT: 5433
  POSTGRES_HOST: "localhost"
#SECRET_KEY: "test_secret_key"
#HASH_KEY: "fuyoqct48b7qTRX37INOI3FQW4CPTY8MGROX8 NOIR4"